# Generated by Django 6.0 on 2025-12-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=70)),
                ('child', models.CharField(max_length=70)),
                ('comment', models.CharField(max_length=250)),
                ('move', models.CharField(max_length=16)),
            ],
        ),
    ]
