# Generated by Django 6.0 on 2025-12-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='line',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='variation',
            field=models.CharField(default=' ', max_length=32),
            preserve_default=False,
        ),
    ]
