# Generated by Django 6.0 on 2025-12-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0002_move_line_move_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='child',
        ),
        migrations.RemoveField(
            model_name='move',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='move',
            name='move',
        ),
        migrations.RemoveField(
            model_name='move',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='move',
            name='variation',
        ),
        migrations.AddField(
            model_name='move',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
