# Generated by Django 6.0 on 2025-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0003_remove_move_child_remove_move_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
