# Generated by Django 6.0 on 2025-12-10 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0004_alter_move_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
