# Generated by Django 6.0 on 2025-12-10 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0005_alter_move_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board', models.CharField(max_length=72)),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='child',
            field=models.CharField(default=' ', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='comment',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='move',
            field=models.CharField(default=' ', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='parent',
            field=models.CharField(default=' ', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='variation',
            field=models.CharField(default=' ', max_length=32),
            preserve_default=False,
        ),
    ]
