# Generated by Django 6.0 on 2025-12-11 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0006_position_move_child_move_comment_move_move_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_position', to='openings.position'),
        ),
        migrations.AlterField(
            model_name='move',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='move',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_position', to='openings.position'),
        ),
    ]
