# Generated by Django 6.0 on 2025-12-11 03:25

from django.db import migrations
from uuid import UUID

def makeStartingPosition(apps, schema_editor):
    Position = apps.get_model("openings", "Position")
    Position.objects.update_or_create(
        id=UUID("00000000-0000-0000-0000-000000000000"),
        defaults={"board": "snbqjbnspppppppp                                PPPPPPPPSNBQJBNS0@"}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0007_alter_move_child_alter_move_id_alter_move_parent'),
    ]

    operations = [
        migrations.RunPython(makeStartingPosition),
    ]
