# Generated by Django 6.0 on 2025-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openings', '0008_auto_20251211_0325'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='move',
            constraint=models.UniqueConstraint(fields=('line', 'parent', 'child'), name='unique_line_parent_child'),
        ),
    ]
